version: '3.8'

services:
  websocket-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=
      - WS_PORT=8080
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M